### ISSUE TITLE
Model  default-2021-03-09 vs sbb_binarization in ocrd_all 

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/sbb_binarization#68]
```
$ ocrd resmgr download ocrd-sbb-binarize default-2021-03-09
14:29:34.198 INFO ocrd.cli.resmgr - Downloading registered resource 'default-2021-03-09' (https://github.com/qurator-spk/sbb_binarization/releases/download/v0.0.11/saved_model_2021_03_09.zip)
```
```
$ ocrd-sbb-binarize -P model default-2021-03-09 -I OCR-D-IMG -O TEST-OCRD-SBB-BINARIZE
Traceback (most recent call last):
  File "/usr/local/bin/ocrd-sbb-binarize", line 33, in <module>
    sys.exit(load_entry_point('sbb-binarization', 'console_scripts', 'ocrd-sbb-binarize')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/build/sbb_binarization/sbb_binarize/ocrd_cli.py", line 162, in cli
    return ocrd_cli_wrap_processor(SbbBinarizeProcessor, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ocrd/decorators/__init__.py", line 133, in ocrd_cli_wrap_processor
    run_processor(processorClass, mets_url=mets, workspace=workspace, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ocrd/processor/helpers.py", line 87, in run_processor
    processor = get_processor(
  File "/usr/local/lib/python3.8/site-packages/ocrd/processor/helpers.py", line 401, in get_processor
    return processor_class(
  File "/build/sbb_binarization/sbb_binarize/ocrd_cli.py", line 49, in __init__
    self.setup()
  File "/build/sbb_binarization/sbb_binarize/ocrd_cli.py", line 72, in setup
    self.binarizer = SbbBinarizer(model_dir=model_path, logger=LOG)
  File "/build/sbb_binarization/sbb_binarize/sbb_binarize.py", line 44, in __init__
    self.models.append(self.load_model(model_file))
  File "/build/sbb_binarization/sbb_binarize/sbb_binarize.py", line 59, in load_model
    model = load_model(model_name, compile=False)
  File "/usr/local/lib/python3.8/site-packages/keras/src/saving/saving_api.py", line 238, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/usr/local/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/site-packages/keras/src/utils/generic_utils.py", line 102, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)
```

Version 0.1.0, ocrd/core 2.63.3

Note that this is Python 3.8, might be relevant. Tested with ocrd/all:maximum Docker image. 

(default works fine.)

**Comment by mikegerber** [comment]
I haven't checked the files in https://qurator-data.de/sbb_binarization/2021-03-09/, so there's another copy...
